shetabit/payment

src/InvoiceBuilder.php
src/PaymentManager.php

@khanzadimahdi requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/shetabit/payment/

Scrutinizer Auto-Fixes

---

README.md
src/Drivers/Irankish.php
src/Drivers/Yekpay.php
src/Drivers/Zarinpal.php
src/Invoice.php

Added RefID property to invoice. Some drivers now set RefID to invoice after payment.

Added RefID to invoices

---

src/Provider/PaymentServiceProvider.php

fixed php artisan view:cache
fixes #34 
closes #34

fix view:cache issue

---

README-FA.md
README.md

Describe your changes in detail.
Improved the documentations
I've proofread it myself.
N/A
- Fixed typos
- Improved sentences
- Replaced # with // in the php comments for consistency
Go over all the following points, and put an `x` in all the boxes that apply.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).
- [ x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [ x] My pull request …

Improve English and Persian documentations

---

src/Drivers/Zarinpal/Zarinpal.php

Add error code when we throw InvalidPaymentException.
This will allow users to  customise the error message using the error code and provide better user excperience based on that.
I've tested the code and it doesn't effect the existing users.

Add exception error code

---

config/payment.php
src/Drivers/Behpardakht/Behpardakht.php

Describe your changes in detail.
Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
Go over all the following points, and put an `x` in all the boxes that apply.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous …

Fix Melat Payment

---

README-ZH.md

add chinese docs.
I plan to add Payment institutions in China in the future
No test required
Go over all the following points, and put an `x` in all the boxes that apply.

chinese docs

---

config/payment.php

Update PayPing's API endpoints to `v2` according to [Official Documents](https://docs.payping.ir/#tag/Payment).

Update Payping gateway to v2 (بروز رسانی درگاه پی پینگ به ورژن 2)

---

README-FA.md
README-ZH.md
README.md

<div dir="rtl">
<p>
سلام
<br>
درگاه دیجی پی به داکیومنت اضافه کردم
</p>
</div>

Add Digipay gateway to Document

---

README-FA.md
README-ZH.md
README.md

اضافه کردن درگاه پرداخت سپرده به داکیومنت

Add Sepordeh driver

---

README-FA.md
README-ZH.md
README.md

added atipay to README files
Why is this change required? What problem does it solve?
it will add atipay to README files.
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
Go over all the following points, and put an `x` in all the boxes that apply.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style …

Update README files

---

composer.json

Add Laravel 9.0 Support

---

README-FA.md
README.md

Add Sizpay driver doc

---

src/Provider/PaymentServiceProvider.php

fix Local driver bug

---

src/Provider/PaymentServiceProvider.php

`Str::replace` introduced in Laravel 8.41.0, we should also support lower versions.

Use str_replace instead of Str::replace

---

composer.json

Add PHPUnit 10

---

src/Facade/Payment.php

It's better to add return type for better auto completion in our dock block

Update dock block

---

README-FA.md
README-ZH.md
README.md

Jibit gateway has been added in the docs regarding the following PR:
https://github.com/shetabit/multipay/pull/218

Add Jibit gateway

---

README.md
composer.json

The package must be on the PHP 8.0 .

Upgrade to PHP 8.0

---

.gitignore
.phpunit.result.cache
.travis.yml
composer.json
phpunit.xml

سلام
طبق کامیت https://github.com/shetabit/multipay/pull/267 این پکیج هم به نسخه php8 آپگرید شد.

update php version and other dependencies

---

composer.json

سلام
متاسفانه توی اصلاح کانفلیکت این پول ریکوئست (https://github.com/shetabit/payment/pull/333) اشتباها موارد مربوط به لاراول 12 رو پاک کرده بودم که الان اصلاح شد.
🙏

support laravel 12
